-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: ''  # Use the sha / tag you want to point at
    hooks:
    -   id: eslint
        types_or: [javascript, jsx, ts, tsx, vue]
        types: [file]
        additional_dependencies:
            -   eslint@7.23.0
            -   eslint-config-airbnb-base@14.2.1
            -   eslint-plugin-vue@7.8.0
            -   eslint-plugin-import@2.22.1