version: '3.9'

services:
  vueapp:
    build:
      context: .
      target: dev
    command: npm run dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file: .env
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
